name: Build Application

on:
  #-- push:
    #-- branches: [ master ]
  #release:
  #  types: [published]
  workflow_dispatch:
  #  inputs:
  #    tags:
  #      description: 'Tag list'
  #      required: true
  #      default: 'latest'

jobs:

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build in GitHub
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          image_name: giuaschool
          image_tag: latest
          dockerfile: ./docker/Dockerfile

      - name: Build in DockerHub
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          image_name: trinkodok/giuaschool
          image_tag: latest
          dockerfile: ./docker/Dockerfile
