name: Build

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]

jobs:

  build:
    name: Build and create a release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image on push event
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          context: .
          file: tests/docker/Dockerfile
          push: true
          tags: |
            trinkodok/giuaschool:latest
            ghcr.io/trinko/giuaschool:latest

      - name: Get latest release tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: github.event_name == 'workflow_run'

      - name: Build and publish image on release event
        uses: docker/build-push-action@v2
        if: github.event_name == 'workflow_run'
        with:
          context: .
          file: tests/docker/Dockerfile
          push: true
          tags: |
            trinkodok/giuaschool:latest
            trinkodok/giuaschool:${{ steps.get-latest-tag.outputs.tag }}
            ghcr.io/trinko/giuaschool:latest
            ghcr.io/trinko/giuaschool:${{ steps.get-latest-tag.outputs.tag }}

      - name: Archive release
        run: |
          docker run --name "gs_release" ghcr.io/trinko/giuaschool:latest tests/docker/entrypoint-release.sh
          docker cp gs_release:/var/www/giuaschool/giuaschool-release.zip giuaschool-release.zip
          mkdir builds
          cp giuaschool-release.zip builds/giuaschool-build-latest.zip

      - name: Upload latest build
        uses: EndBug/add-and-commit@v7
        if: github.event_name == 'push'
        with:
          add: builds/giuaschool-build-latest.zip --force
          branch: builds
          branch_mode: create
          push: '--force --set-upstream origin builds'
          pull: 'NO-PULL'
          default_author: github_actor
          message: 'Upload latest build'

      - name: Publish latest release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'workflow_run'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: giuaschool-release.zip
          asset_name: giuaschool-release-latest.zip
          tag: ${{ steps.get-latest-tag.outputs.tag }}
