name: Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Build & push image on DockerHub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: trinkodok/giuaschool
          registry: docker.io
          dockerfile: ./docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build & push image on GitHub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: trinko/giuaschool
          registry: docker.pkg.github.com
          dockerfile: ./docker/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      
      
      #- name: Push to Docker Hub
      #  uses: docker/build-push-action@v1
      #  with:
      #    dockerfile: ./docker/Dockerfile
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    repository: trinkodok/giuaschool
      #    tag_with_ref: true
                       
      #- name: Push to GitHub Packages
      #  #id: docker_build
      #  uses: docker/build-push-action@v1
      #  with: 
      #    dockerfile: ./docker/Dockerfile
          #tags: trinko/giuaschool:latest 
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      #    registry: docker.pkg.github.com
      #    repository: trinko/giuaschool/giuaschool-test
      #    tag_with_ref: true

      #- name: Image digest
      #  run: echo ${{ steps.docker_build.outputs.digest }}
        
