name: Test updates

on:
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get latest release tag
        id: latest-release
        uses: jossef/action-latest-release-info@v1.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Test update procedure
        run: |
          VERSIONE="${{ steps.latest-release.outputs.tag_name }}"
          docker run -d --rm --name gs_update --add-host=giuaschool_test:127.0.0.1 --add-host=chrome_headless:127.0.0.1 ghcr.io/iisgiua/giuaschool-test:${VERSIONE:1}
          docker cp tests/docker/test-update.sh gs_update:/var/www/giuaschool/tests/docker/
          docker exec gs_update tests/docker/ ${VERSIONE:1}
