name: Test giua@school

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Test on Symfony 4.4 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: giuaschool
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pcre, session, tokenizer
          coverage: xdebug
          tools: composer:v1

      - name: Check PHP
        run: php -r "phpInfo();"


      #-- - name: Get composer cache directory
        #-- id: composer-cache
        #-- run: echo "::set-output name=dir::$(composer config cache-files-dir)"
 #--
      #-- - name: Cache composer dependencies
        #-- uses: actions/cache@v2
        #-- with:
          #-- path: ${{ steps.composer-cache.outputs.dir }}
          #-- # Use composer.json for key, if composer.lock is not committed.
          #-- # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          #-- key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          #-- restore-keys: ${{ runner.os }}-composer-
     #--
      #-- - name: Install Composer dependencies
        #-- run: |
          #-- composer require --dev symfony/orm-pack symfony/phpunit-bridge
          #-- composer install --no-progress --prefer-dist --optimize-autoloader
          #-- #php vendor/bin/phpunit install
     #--
      #- name: Run Migration
      #  run: |
      #    php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
      #    php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
      #  env:
      #    DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony

      #-- - name: Run Tests
        #-- run: php vendor/bin/simple-phpunit
        #-- #run: php bin/phpunit --coverage-text
